name: mutation-effect-prediction
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - biopython
  - scipy
  - pip
  - pip:
      - py3Dmol